### ISSUE TITLE
calling `distance` with certain inputs never returns

### ISSUE THREAD

**Issue by neilberkman** [preciz/levenshtein#1]
`Levenshtein.distance("middlesex 5", "suffolk and middlesex 2")` seems to hang indefinitely - at least, my CPU has been pegged for several minutes at this point and it's still running.

**Comment by preciz** [comment]
I was able to reproduce the problem.

I have changed the Erlang implementation to an Elixir one.
This was removed form the Elixir source code in 2015 due they changed to Jaro-Winkler distance.

This one works fine and is fast.

Please update to v0.3.0. Thank you!
