### ISSUE TITLE
performance comparison

### ISSUE THREAD

**Issue by shribe** [preciz/levenshtein#29]
Just did a quick performance comparison to other implementations, using:

```elixir
  def test_levenshtein(words, fun) do
    Enum.reduce(words, %{}, fn (word1, map) ->
      Enum.reduce(words, map, fn (word2, map) ->
        Map.put(map, {word1, word2}, fun.(word1, word2))
      end)
    end) #|> IO.inspect
  end
```

with 100 words pulled from a database of names.

Levenshtein: 0.020s
Leven: 0.062s
ExLevenshtein: 39.9s
Levy: 109s

With 1,000 & 10,000 words, the relationship between Levenshtein & Leven is the same. You can guess why I didn't test the other 2 with more words ;-)

**Comment by preciz** [comment]
Thank you.
(This repo contains the original https://github.com/elixir-lang/elixir implementation which was removed)
